version: "1.0"
info:
  model: int-scaffold
packages:
- name: SDBITEDIMonitorProducerProject
  gitServerName: sdbit_github
  gitUrl: https://github.com/wm-sdbit
  gitUsername: wm-sdbit
  gitBranch: main
services:
- serviceName: project.sdbitedimonitorproducer.integrations:OutMessagePublisher
  packages:
  - name: SDBITEDIMonitorProducerProject
    version: "1.0"
